# PostgreSQL
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: sftest_development

test:
  <<: *default
  database: sftest_test

production:
  <<: *default
  # database: blog_rails6_production
  url: <%= ENV['DATABASE_URL'] %>
